name: $(Year:yyyy).$(Month).$(DayOfMonth).$(rev:r)

resources:
- repo: self
  clean: true

trigger:
    branches:
        include:
        - master
        - feature/*
        - bug/*
        exclude:
        - dummy/*

phases:

- phase: Phase_1
  displayName: Phase Windows
  condition: succeeded()
  
  queue:
    name: Hosted VS2017
    demands: npm

  variables:
    angular_version: '6.1.7'

  steps:
  
  # Perform npm Install
  - task: Npm@1
    displayName: 'Install'
    inputs:
      workingDir: Application
      verbose: false

  # Perform Angular Tests
  - task: Npm@1
    displayName: 'Test'
    inputs:
      workingDir: Application
      command: custom
      verbose: false
      customCommand: 'test'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))   

  # Attach Test Report to Azure Pipeline
  - task: PublishTestResults@2
    displayName: 'Report Tests'
    inputs:
      testRunner: NUnit
      testResultsFiles: Application/Reports/Results.xml
      mergeTestResults: true
      testRunTitle: 'Microsoft Account Profile Information'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))   

  # Attach Coverage Report to Azure Pipeline
  - task: PublishCodeCoverageResults@1
    displayName: 'Report Coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/Application/Reports/Coverage/cobertura-coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/Application/Reports/Coverage'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest')) 

  # Perform Angular Build
  - task: Npm@1
    displayName: 'Build'
    inputs:
      workingDir: Application
      command: custom
      verbose: false
      customCommand: 'run build'

  # Copy Build Output
  - task: CopyFiles@2
    displayName: 'Copy'
    inputs:
      SourceFolder: Application/Distributions
      Contents: |
       **
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
      flattenFolders: true
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual'))

  # Attach Build Output to Azure Pipeline
  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: Drop
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual'))
